### ISSUE TITLE
Fails to check state of pool before trying to create.

### ISSUE THREAD

**Issue by pryorda** [DealerDotCom/terraform-provider-bigip#25] opened 2016-06-15 21:53 UTC
I have a pool that already exists and trying to update it. I get the following

```
dpryor@co007-linux:~/git/terraform-bigip$ terraform apply
var.password
  BigIp User Password

  Enter a value: password

bigip_ltm_monitor.monitor: Refreshing state... (ID: /Common/address_verification_api)
bigip_ltm_pool.address_verification_api: Creating...
  allow_nat:           "" => "true"
  allow_snat:          "" => "true"
  load_balancing_mode: "" => "least-connections-member"
  monitors.#:          "" => "1"
  monitors.819763366:  "" => "/Common/address_verification_api"
  name:                "" => "/Common/beta_address_verification_api"
  nodes.#:             "" => "2"
  nodes.1354786338:    "" => "/Common/sbeta1a:8225"
  nodes.1630043327:    "" => "/Common/sbeta2a:8225"
Error applying plan:

1 error(s) occurred:

* bigip_ltm_pool.address_verification_api: 01020066:3: The requested Pool (/Common/beta_address_verification_api) already exists in partition Common.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
dpryor@co007-linux:~/git/terraform-bigip$ 
```

**Comment by pryorda** [comment] 2016-06-15 22:12
Looks like when it says creating irule it does the same thing (except this is gracefully ignored). I think both of these should check if they exist first.

**Comment by aburnett** [comment] 2016-06-16 15:24
Terraform does not currently support importing existing resources. See [this issue](https://github.com/hashicorp/terraform/issues/581).

**Comment by aburnett** [comment] 2016-06-16 15:26
Oh, and I just now see this support has been added for the next version! I'll reopen this and we can use it to track updating the plugin to support the new API when it is available.

**Comment by pryorda** [comment] 2016-06-16 16:48
next version == 0.7?

**Comment by aburnett** [comment] 2016-06-16 17:26
Yes. Support is already in master, so we could start developing now...

https://godoc.org/github.com/hashicorp/terraform/helper/schema#ResourceImporter

**Comment by pryorda** [comment] 2016-06-17 14:30
I started some work over in my repo and I'm running into this? Im not a go dev so any help would be appreciated. 

https://gist.github.com/pryorda/6234a1fc973efab5ad0b1fb5d92ba71f

**Comment by pryorda** [comment] 2016-06-17 15:06
I have the import working via and will have a pr shortly. Can you tell me where the force destroy gets set?

```
dpryor@co007-linux:~/git/terraform-ava-beta$ terraform apply
var.password
  BigIp User Password

  Enter a value: 

bigip_ltm_monitor.monitor: Refreshing state... (ID: /Common/address_verification_api)
bigip_ltm_pool.address_verification_api: Refreshing state... (ID: /Common/beta_address_verification_api)
bigip_ltm_pool.address_verification_api: Destroying...
Error applying plan:

1 error(s) occurred:

* bigip_ltm_pool.address_verification_api: 01070340:3: pool (/Common/beta_address_verification_api) is referenced by one or more rules

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
dpryor@co007-linux:~/git/terraform-ava-beta$ 
```

**Comment by pryorda** [comment] 2016-06-17 17:42
Removed ForceNew on the name and Created PR.
Pull Request #26

**Comment by pryorda** [comment] 2016-06-18 20:53
PR Should be completely ready. Had to fix some name issues and added more importers

**Comment by aburnett** [comment] 2016-09-13 02:06
Closing due to expected behavior. Support being added to handle import of existing infrastructure.

**Closed as completed by aburnett** 2016-09-13 02:06 UTC
